apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
    - name: hello-world-container
      image: madanmohan7793/myapp:hello-world # Using nginx as a basic web server image ......
      ports:
        - containerPort: 80
