apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container
          image: madanmohan7793/myapp:hello-world  # Ensure this is the latest image tag
          ports:
            - containerPort: 80
          imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
