apiVersion: v1
kind: Pod
metadata:
  name: hello-world-testing  # Name of the Pod
  labels:
    app: hello-world         # Label for identifying the app
spec:
  containers:
    - name: hello-world-container
      image: madanmohan7793/myapp:v2 # Ensure this is the latest image tag
      ports:
        - containerPort: 80  # The port the container listens on
      imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
